"""crear tablas

Revision ID: 4ad42ce8e364
Revises: 793135c95d6f
Create Date: 2025-03-21 19:35:09.515780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad42ce8e364'
down_revision: Union[str, None] = '793135c95d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approachs',
    sa.Column('approach_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('approach_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('USER', 'PSYCHOLOGIST', name='tipousuario'), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('psychologists',
    sa.Column('psychologist_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('experiencia', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('psychologist_id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conexion_approachs',
    sa.Column('conexion_approach_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approach_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['approach_id'], ['approachs.approach_id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('conexion_approach_id'),
    sa.UniqueConstraint('approach_id'),
    sa.UniqueConstraint('psychologist_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('psicologo_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psychologists.psychologist_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('conexion_approachs')
    op.drop_table('psychologists')
    op.drop_table('users')
    op.drop_table('approachs')
    # ### end Alembic commands ###
