"""Agregar cascada a la relación entre User y Psychologist

Revision ID: bd309c1a0a61
Revises: 2f6562ee06a3
Create Date: 2025-03-22 13:20:13.429310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd309c1a0a61'
down_revision: Union[str, None] = '2f6562ee06a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
