"""Correccion de unicidad de las claves foraneas en conexion_approach

Revision ID: cc1af99a4ceb
Revises: bd309c1a0a61
Create Date: 2025-03-26 20:36:31.173821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1af99a4ceb'
down_revision: Union[str, None] = 'bd309c1a0a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conexion_approachs', 'psychologists', ['psychologist_id'], ['psychologist_id'])
    op.create_foreign_key(None, 'conexion_approachs', 'approachs', ['approach_id'], ['approach_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conexion_approachs', type_='foreignkey')
    op.drop_constraint(None, 'conexion_approachs', type_='foreignkey')
    # ### end Alembic commands ###
